import math

print("Enter length of the first side: ")
a = input()
a = float(a)
print("noted!")
print("Enter length of the first side: ")
b = input()
b = float(b)
print("noted!")
print("Enter degree of the angle between sides: ")
ang = input()
ang = float(ang)
print("noted!")
print("processing...")
c = math.sqrt((a**2)+(b**2)-(2*a*b*math.cos(math.radians(ang))))
print("done!")
print("- - -")
print("a = ", a)
print("b = ", b)
print("ang = ", ang)
print("c = ", c)
